# SPDX-FileCopyrightText: 2023, 2025 Jean-Philippe Cugnet <jean-philippe@cugnet.eu>
# SPDX-License-Identifier: GPL-3.0-only

[[syntax]]
name = "template"
block_start = "(%"
block_end = "%)"
comment_start = "(#"
comment_end = "#)"
expr_start = "(("
expr_end = "))"
