# SPDX-FileCopyrightText: 2023-2025 Jean-Philippe Cugnet <jean-philippe@cugnet.eu>
# SPDX-License-Identifier: EUPL-1.2

allow-unwrap-in-tests = true
allowed-idents-below-min-chars = ["c", "i", "j", "n", "s"]
check-private-items = true
# NOTE: ".." indicates that default values should be included.
doc-valid-idents = [".."]
