allowed-duplicate-crates = [
    "bitflags",
    "regex-automata",
    "regex-syntax",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]

allowed-idents-below-min-chars = ["c", "i", "j", "n", "s"]
check-private-items = true
# NOTE: ".." indicates that default values should be included.
doc-valid-idents = [".."]
