# SPDX-FileCopyrightText: 2025 Jean-Philippe Cugnet <jean-philippe@cugnet.eu>
# SPDX-License-Identifier: EUPL-1.2

[graph]
all-features = true

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "MPL-2.0"]
confidence-threshold = 0.8
exceptions = [
    # Allow licenses for specific crates.
    { crate = "git-z", allow = ["GPL-3.0-only"] },
    { crate = "unicode-ident", allow = ["Unicode-3.0"] },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow = []
deny = []
skip = [
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
