#!/bin/sh

## git-z - A Git extension to go beyond.
## Copyright (C) 2024 Jean-Philippe Cugnet <jean-philippe@cugnet.eu>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, version 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <https://www.gnu.org/licenses/>.

##
## A fake Git command used for testing.
##

commit() {
    echo "fake commit"
    echo -e "$@" > .git/commit
}

branch() {
    case "$@" in
        "branch --show-current")
            if [ -f .git/branch ]; then
                echo $(< .git/branch)
            else
                echo "main"
            fi
            ;;
    esac
}

rev_parse() {
    case "$@" in
        "rev-parse --show-toplevel")
            pwd
            ;;
        "rev-parse --is-inside-work-tree")
            echo "true"
            ;;
    esac
}

case $1 in
    commit)
        commit "$@"
        ;;
    branch)
        branch "$@"
        ;;
    rev-parse)
        rev_parse "$@"
        ;;
esac
