[alias]
xtask = "run --package xtask --"

# Ensure the binary is statically linked when using musl so that it is actually
# portable.
[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-self-contained=yes",
]

# Ensure the binary is statically linked on Windows as well so that it does not
# depend on the vcruntime DLL (installed by Visual C++ Redistribuable, but not
# available on fresh installs).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
