# SPDX-FileCopyrightText: 2024-2025 Jean-Philippe Cugnet <jean-philippe@cugnet.eu>
# SPDX-License-Identifier: EUPL-1.2

name: CI

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
      - bugfix/*
      - hotfix/*
      - docs/*
      - chore/*
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1
  IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}

jobs:
  commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment
        run: nix build -L --no-link .#devShells.x86_64-linux.ci-commits
      - name: Run the commit linter
        run: nix develop .#ci-commits -c cargo xtask check commits

  licenses:
    name: Licensing
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment
        run: nix build -L --no-link .#devShells.x86_64-linux.ci-license
      - name: Check licensing compliance
        run: nix develop .#ci-license -c cargo xtask check licenses

  format:
    name: Code formatting and typos
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment
        run: nix build -L --no-link .#devShells.x86_64-linux.ci-format
      - name: Check the code is formatted and free of typos
        run: nix develop .#ci-format -c cargo xtask check format

  build:
    name: Compilation and static analysis
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-darwin
            runner: macos-latest
          - system: x86_64-windows
            runner: windows-latest
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        if: matrix.system != 'x86_64-windows'
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: |
          nix build -L --no-link .#devShells.${{ matrix.system }}.ci-code
      - name: Setup the environment (without Nix)
        if: matrix.system == 'x86_64-windows'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - name: Restore the build cache
        uses: actions/cache/restore@v4
        with:
          key: rust-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/
      - name: Compile and run static analysis (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: nix develop .#ci-code -c cargo xtask check build
      - name: Compile and run static analysis (without Nix)
        if: matrix.system == 'x86_64-windows'
        run: cargo xtask check build
      - name: Save the build cache
        uses: actions/cache/save@v4
        with:
          key: rust-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/

  docs:
    name: Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment
        run: nix build -L --no-link .#devShells.x86_64-linux.ci-code
      - name: Restore the build cache
        uses: actions/cache/restore@v4
        with:
          key: rust-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/
      - name: Check the documentation
        run: nix develop .#ci-code -c cargo xtask check doc

  test:
    name: Tests
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-darwin
            runner: macos-latest
          - system: x86_64-windows
            runner: windows-latest
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        if: matrix.system != 'x86_64-windows'
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: |
          nix build -L --no-link .#devShells.${{ matrix.system }}.ci-code
      - name: Setup the environment (without Nix)
        if: matrix.system == 'x86_64-windows'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack,cargo-nextest
      - name: Restore the build cache
        uses: actions/cache/restore@v4
        with:
          key: rust-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/
      - name: Build and run the tests (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: nix develop .#ci-code -c cargo xtask check test
      - name: Build and run the tests (without Nix)
        if: matrix.system == 'x86_64-windows'
        run: cargo xtask check test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment
        run: nix build -L --no-link .#devShells.x86_64-linux.ci-coverage
      - name: Restore the build cache
        uses: actions/cache/restore@v4
        with:
          key: rust-coverage-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/
      - name: Generate the test coverage report
        run: nix develop .#ci-coverage -c cargo xtask check coverage
      - name: Upload the test coverage report
        uses: codecov/codecov-action@v5
        with:
          disable_search: true
          files: ./target/cobertura.xml
          fail_ci_if_error: true
          use_oidc: true
      - name: Save the build cache
        uses: actions/cache/save@v4
        with:
          key: rust-coverage-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment
        run: nix build -L --no-link .#devShells.x86_64-linux.ci-security
      - name: Run security checks
        run: nix develop .#ci-security -c cargo xtask check security

  deps:
    name: Dependencies
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-darwin
            runner: macos-latest
          - system: x86_64-windows
            runner: windows-latest
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        if: matrix.system != 'x86_64-windows'
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: nix build -L --no-link .#devShells.${{ matrix.system }}.ci-deps
      - name: Install the Rust toolchain (without Nix)
        if: matrix.system == 'x86_64-windows'
        run: rustup toolchain install nightly
      - name: Setup the environment (without Nix)
        if: matrix.system == 'x86_64-windows'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-hack,cargo-udeps
      - name: Restore the build cache
        uses: actions/cache/restore@v4
        with:
          key: rust-udeps-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/
      - name: Check the dependencies (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: nix develop .#ci-deps -c cargo xtask check deps
      - name: Check the dependencies (without Nix)
        if: matrix.system == 'x86_64-windows'
        run: cargo +nightly xtask check deps
      - name: Save the build cache
        uses: actions/cache/save@v4
        with:
          key: rust-udeps-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/

  packages:
    name: Packages
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-darwin
            runner: macos-latest
          - system: x86_64-windows
            runner: windows-latest
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        if: matrix.system != 'x86_64-windows'
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup the environment (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: |
          nix build -L --no-link .#devShells.${{ matrix.system }}.ci-code
      - name: Setup the environment (without Nix)
        if: matrix.system == 'x86_64-windows'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-wix
      - name: Restore the build cache
        uses: actions/cache/restore@v4
        with:
          key: rust-${{ matrix.system }}-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            target/
      - name: Build the packages (with Nix)
        if: matrix.system != 'x86_64-windows'
        run: nix develop .#ci-code -c cargo xtask check packages
      - name: Build the packages (without Nix)
        if: matrix.system == 'x86_64-windows'
        run: cargo xtask check packages
